//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_ComentarioUserId", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaIS.Model.UserProfile), "Comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaIS.Model.Comentario), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_FavoritoUserId", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaIS.Model.UserProfile), "Favorito", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaIS.Model.Favorito), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_ValoracionUsrId", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaIS.Model.UserProfile), "Valoracion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaIS.Model.Valoracion), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.PracticaIS.Model", "ComentarioEtiqueta", "Comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaIS.Model.Comentario), "Etiqueta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaIS.Model.Etiqueta))]

#endregion

namespace Es.Udc.DotNet.PracticaIS.Model
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class OpinadorEntitiesContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto OpinadorEntitiesContainer usando la cadena de conexión encontrada en la sección 'OpinadorEntitiesContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public OpinadorEntitiesContainer() : base("name=OpinadorEntitiesContainer", "OpinadorEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto OpinadorEntitiesContainer.
        /// </summary>
        public OpinadorEntitiesContainer(string connectionString) : base(connectionString, "OpinadorEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto OpinadorEntitiesContainer.
        /// </summary>
        public OpinadorEntitiesContainer(EntityConnection connection) : base(connection, "OpinadorEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Comentario> Comentarios
        {
            get
            {
                if ((_Comentarios == null))
                {
                    _Comentarios = base.CreateObjectSet<Comentario>("Comentarios");
                }
                return _Comentarios;
            }
        }
        private ObjectSet<Comentario> _Comentarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Etiqueta> Etiquetas
        {
            get
            {
                if ((_Etiquetas == null))
                {
                    _Etiquetas = base.CreateObjectSet<Etiqueta>("Etiquetas");
                }
                return _Etiquetas;
            }
        }
        private ObjectSet<Etiqueta> _Etiquetas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Favorito> Favoritoes
        {
            get
            {
                if ((_Favoritoes == null))
                {
                    _Favoritoes = base.CreateObjectSet<Favorito>("Favoritoes");
                }
                return _Favoritoes;
            }
        }
        private ObjectSet<Favorito> _Favoritoes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UserProfile> UserProfiles
        {
            get
            {
                if ((_UserProfiles == null))
                {
                    _UserProfiles = base.CreateObjectSet<UserProfile>("UserProfiles");
                }
                return _UserProfiles;
            }
        }
        private ObjectSet<UserProfile> _UserProfiles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Valoracion> Valoracions
        {
            get
            {
                if ((_Valoracions == null))
                {
                    _Valoracions = base.CreateObjectSet<Valoracion>("Valoracions");
                }
                return _Valoracions;
            }
        }
        private ObjectSet<Valoracion> _Valoracions;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Comentarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToComentarios(Comentario comentario)
        {
            base.AddObject("Comentarios", comentario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Etiquetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEtiquetas(Etiqueta etiqueta)
        {
            base.AddObject("Etiquetas", etiqueta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Favoritoes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFavoritoes(Favorito favorito)
        {
            base.AddObject("Favoritoes", favorito);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UserProfiles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUserProfiles(UserProfile userProfile)
        {
            base.AddObject("UserProfiles", userProfile);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Valoracions. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToValoracions(Valoracion valoracion)
        {
            base.AddObject("Valoracions", valoracion);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.PracticaIS.Model", Name="Comentario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comentario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Comentario.
        /// </summary>
        /// <param name="comentarioId">Valor inicial de la propiedad comentarioId.</param>
        /// <param name="texto">Valor inicial de la propiedad texto.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="usrId">Valor inicial de la propiedad usrId.</param>
        /// <param name="productoId">Valor inicial de la propiedad productoId.</param>
        public static Comentario CreateComentario(global::System.Int64 comentarioId, global::System.String texto, global::System.DateTime fecha, global::System.Int64 usrId, global::System.Int64 productoId)
        {
            Comentario comentario = new Comentario();
            comentario.comentarioId = comentarioId;
            comentario.texto = texto;
            comentario.fecha = fecha;
            comentario.usrId = usrId;
            comentario.productoId = productoId;
            return comentario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 comentarioId
        {
            get
            {
                return _comentarioId;
            }
            set
            {
                if (_comentarioId != value)
                {
                    OncomentarioIdChanging(value);
                    ReportPropertyChanging("comentarioId");
                    _comentarioId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("comentarioId");
                    OncomentarioIdChanged();
                }
            }
        }
        private global::System.Int64 _comentarioId;
        partial void OncomentarioIdChanging(global::System.Int64 value);
        partial void OncomentarioIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String texto
        {
            get
            {
                return _texto;
            }
            set
            {
                OntextoChanging(value);
                ReportPropertyChanging("texto");
                _texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("texto");
                OntextoChanged();
            }
        }
        private global::System.String _texto;
        partial void OntextoChanging(global::System.String value);
        partial void OntextoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 usrId
        {
            get
            {
                return _usrId;
            }
            set
            {
                OnusrIdChanging(value);
                ReportPropertyChanging("usrId");
                _usrId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usrId");
                OnusrIdChanged();
            }
        }
        private global::System.Int64 _usrId;
        partial void OnusrIdChanging(global::System.Int64 value);
        partial void OnusrIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 productoId
        {
            get
            {
                return _productoId;
            }
            set
            {
                OnproductoIdChanging(value);
                ReportPropertyChanging("productoId");
                _productoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productoId");
                OnproductoIdChanged();
            }
        }
        private global::System.Int64 _productoId;
        partial void OnproductoIdChanging(global::System.Int64 value);
        partial void OnproductoIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_ComentarioUserId", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_ComentarioUserId", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_ComentarioUserId", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_ComentarioUserId", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_ComentarioUserId", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.PracticaIS.Model", "ComentarioEtiqueta", "Etiqueta")]
        public EntityCollection<Etiqueta> Etiquetas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Etiqueta>("Es.Udc.DotNet.PracticaIS.Model.ComentarioEtiqueta", "Etiqueta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Etiqueta>("Es.Udc.DotNet.PracticaIS.Model.ComentarioEtiqueta", "Etiqueta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.PracticaIS.Model", Name="Etiqueta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Etiqueta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Etiqueta.
        /// </summary>
        /// <param name="etiquetaId">Valor inicial de la propiedad etiquetaId.</param>
        /// <param name="tag">Valor inicial de la propiedad tag.</param>
        /// <param name="ocurrencias">Valor inicial de la propiedad ocurrencias.</param>
        public static Etiqueta CreateEtiqueta(global::System.Int64 etiquetaId, global::System.String tag, global::System.Int32 ocurrencias)
        {
            Etiqueta etiqueta = new Etiqueta();
            etiqueta.etiquetaId = etiquetaId;
            etiqueta.tag = tag;
            etiqueta.ocurrencias = ocurrencias;
            return etiqueta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 etiquetaId
        {
            get
            {
                return _etiquetaId;
            }
            set
            {
                if (_etiquetaId != value)
                {
                    OnetiquetaIdChanging(value);
                    ReportPropertyChanging("etiquetaId");
                    _etiquetaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("etiquetaId");
                    OnetiquetaIdChanged();
                }
            }
        }
        private global::System.Int64 _etiquetaId;
        partial void OnetiquetaIdChanging(global::System.Int64 value);
        partial void OnetiquetaIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tag
        {
            get
            {
                return _tag;
            }
            set
            {
                OntagChanging(value);
                ReportPropertyChanging("tag");
                _tag = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tag");
                OntagChanged();
            }
        }
        private global::System.String _tag;
        partial void OntagChanging(global::System.String value);
        partial void OntagChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ocurrencias
        {
            get
            {
                return _ocurrencias;
            }
            set
            {
                OnocurrenciasChanging(value);
                ReportPropertyChanging("ocurrencias");
                _ocurrencias = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ocurrencias");
                OnocurrenciasChanged();
            }
        }
        private global::System.Int32 _ocurrencias;
        partial void OnocurrenciasChanging(global::System.Int32 value);
        partial void OnocurrenciasChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.PracticaIS.Model", "ComentarioEtiqueta", "Comentario")]
        public EntityCollection<Comentario> Comentarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comentario>("Es.Udc.DotNet.PracticaIS.Model.ComentarioEtiqueta", "Comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comentario>("Es.Udc.DotNet.PracticaIS.Model.ComentarioEtiqueta", "Comentario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.PracticaIS.Model", Name="Favorito")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Favorito : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Favorito.
        /// </summary>
        /// <param name="favoritoId">Valor inicial de la propiedad favoritoId.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="comentario">Valor inicial de la propiedad comentario.</param>
        /// <param name="usrId">Valor inicial de la propiedad usrId.</param>
        /// <param name="productoId">Valor inicial de la propiedad productoId.</param>
        public static Favorito CreateFavorito(global::System.Int64 favoritoId, global::System.String nombre, global::System.DateTime fecha, global::System.String comentario, global::System.Int64 usrId, global::System.Int64 productoId)
        {
            Favorito favorito = new Favorito();
            favorito.favoritoId = favoritoId;
            favorito.nombre = nombre;
            favorito.fecha = fecha;
            favorito.comentario = comentario;
            favorito.usrId = usrId;
            favorito.productoId = productoId;
            return favorito;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 favoritoId
        {
            get
            {
                return _favoritoId;
            }
            set
            {
                if (_favoritoId != value)
                {
                    OnfavoritoIdChanging(value);
                    ReportPropertyChanging("favoritoId");
                    _favoritoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("favoritoId");
                    OnfavoritoIdChanged();
                }
            }
        }
        private global::System.Int64 _favoritoId;
        partial void OnfavoritoIdChanging(global::System.Int64 value);
        partial void OnfavoritoIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comentario
        {
            get
            {
                return _comentario;
            }
            set
            {
                OncomentarioChanging(value);
                ReportPropertyChanging("comentario");
                _comentario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comentario");
                OncomentarioChanged();
            }
        }
        private global::System.String _comentario;
        partial void OncomentarioChanging(global::System.String value);
        partial void OncomentarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 usrId
        {
            get
            {
                return _usrId;
            }
            set
            {
                OnusrIdChanging(value);
                ReportPropertyChanging("usrId");
                _usrId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usrId");
                OnusrIdChanged();
            }
        }
        private global::System.Int64 _usrId;
        partial void OnusrIdChanging(global::System.Int64 value);
        partial void OnusrIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 productoId
        {
            get
            {
                return _productoId;
            }
            set
            {
                OnproductoIdChanging(value);
                ReportPropertyChanging("productoId");
                _productoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productoId");
                OnproductoIdChanged();
            }
        }
        private global::System.Int64 _productoId;
        partial void OnproductoIdChanging(global::System.Int64 value);
        partial void OnproductoIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_FavoritoUserId", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_FavoritoUserId", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_FavoritoUserId", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_FavoritoUserId", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_FavoritoUserId", "UserProfile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.PracticaIS.Model", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UserProfile.
        /// </summary>
        /// <param name="usrId">Valor inicial de la propiedad usrId.</param>
        /// <param name="loginName">Valor inicial de la propiedad loginName.</param>
        /// <param name="enPassword">Valor inicial de la propiedad enPassword.</param>
        /// <param name="firstName">Valor inicial de la propiedad firstName.</param>
        /// <param name="lastName">Valor inicial de la propiedad lastName.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="language">Valor inicial de la propiedad language.</param>
        /// <param name="country">Valor inicial de la propiedad country.</param>
        public static UserProfile CreateUserProfile(global::System.Int64 usrId, global::System.String loginName, global::System.String enPassword, global::System.String firstName, global::System.String lastName, global::System.String email, global::System.String language, global::System.String country)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.usrId = usrId;
            userProfile.loginName = loginName;
            userProfile.enPassword = enPassword;
            userProfile.firstName = firstName;
            userProfile.lastName = lastName;
            userProfile.email = email;
            userProfile.language = language;
            userProfile.country = country;
            return userProfile;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 usrId
        {
            get
            {
                return _usrId;
            }
            set
            {
                if (_usrId != value)
                {
                    OnusrIdChanging(value);
                    ReportPropertyChanging("usrId");
                    _usrId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usrId");
                    OnusrIdChanged();
                }
            }
        }
        private global::System.Int64 _usrId;
        partial void OnusrIdChanging(global::System.Int64 value);
        partial void OnusrIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String loginName
        {
            get
            {
                return _loginName;
            }
            set
            {
                OnloginNameChanging(value);
                ReportPropertyChanging("loginName");
                _loginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("loginName");
                OnloginNameChanged();
            }
        }
        private global::System.String _loginName;
        partial void OnloginNameChanging(global::System.String value);
        partial void OnloginNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String enPassword
        {
            get
            {
                return _enPassword;
            }
            set
            {
                OnenPasswordChanging(value);
                ReportPropertyChanging("enPassword");
                _enPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("enPassword");
                OnenPasswordChanged();
            }
        }
        private global::System.String _enPassword;
        partial void OnenPasswordChanging(global::System.String value);
        partial void OnenPasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String language
        {
            get
            {
                return _language;
            }
            set
            {
                OnlanguageChanging(value);
                ReportPropertyChanging("language");
                _language = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("language");
                OnlanguageChanged();
            }
        }
        private global::System.String _language;
        partial void OnlanguageChanging(global::System.String value);
        partial void OnlanguageChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_ComentarioUserId", "Comentario")]
        public EntityCollection<Comentario> Comentarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comentario>("Es.Udc.DotNet.PracticaIS.Model.FK_ComentarioUserId", "Comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comentario>("Es.Udc.DotNet.PracticaIS.Model.FK_ComentarioUserId", "Comentario", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_FavoritoUserId", "Favorito")]
        public EntityCollection<Favorito> Favoritos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Favorito>("Es.Udc.DotNet.PracticaIS.Model.FK_FavoritoUserId", "Favorito");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Favorito>("Es.Udc.DotNet.PracticaIS.Model.FK_FavoritoUserId", "Favorito", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_ValoracionUsrId", "Valoracion")]
        public EntityCollection<Valoracion> Valoraciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Valoracion>("Es.Udc.DotNet.PracticaIS.Model.FK_ValoracionUsrId", "Valoracion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Valoracion>("Es.Udc.DotNet.PracticaIS.Model.FK_ValoracionUsrId", "Valoracion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.PracticaIS.Model", Name="Valoracion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Valoracion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Valoracion.
        /// </summary>
        /// <param name="valoracionId">Valor inicial de la propiedad valoracionId.</param>
        /// <param name="voto">Valor inicial de la propiedad voto.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="usrId">Valor inicial de la propiedad usrId.</param>
        /// <param name="vendedorId">Valor inicial de la propiedad vendedorId.</param>
        public static Valoracion CreateValoracion(global::System.Int64 valoracionId, global::System.Int32 voto, global::System.DateTime fecha, global::System.Int64 usrId, global::System.String vendedorId)
        {
            Valoracion valoracion = new Valoracion();
            valoracion.valoracionId = valoracionId;
            valoracion.voto = voto;
            valoracion.fecha = fecha;
            valoracion.usrId = usrId;
            valoracion.vendedorId = vendedorId;
            return valoracion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 valoracionId
        {
            get
            {
                return _valoracionId;
            }
            set
            {
                if (_valoracionId != value)
                {
                    OnvaloracionIdChanging(value);
                    ReportPropertyChanging("valoracionId");
                    _valoracionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("valoracionId");
                    OnvaloracionIdChanged();
                }
            }
        }
        private global::System.Int64 _valoracionId;
        partial void OnvaloracionIdChanging(global::System.Int64 value);
        partial void OnvaloracionIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 voto
        {
            get
            {
                return _voto;
            }
            set
            {
                OnvotoChanging(value);
                ReportPropertyChanging("voto");
                _voto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("voto");
                OnvotoChanged();
            }
        }
        private global::System.Int32 _voto;
        partial void OnvotoChanging(global::System.Int32 value);
        partial void OnvotoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comentario
        {
            get
            {
                return _comentario;
            }
            set
            {
                OncomentarioChanging(value);
                ReportPropertyChanging("comentario");
                _comentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comentario");
                OncomentarioChanged();
            }
        }
        private global::System.String _comentario;
        partial void OncomentarioChanging(global::System.String value);
        partial void OncomentarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 usrId
        {
            get
            {
                return _usrId;
            }
            set
            {
                OnusrIdChanging(value);
                ReportPropertyChanging("usrId");
                _usrId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usrId");
                OnusrIdChanged();
            }
        }
        private global::System.Int64 _usrId;
        partial void OnusrIdChanging(global::System.Int64 value);
        partial void OnusrIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vendedorId
        {
            get
            {
                return _vendedorId;
            }
            set
            {
                OnvendedorIdChanging(value);
                ReportPropertyChanging("vendedorId");
                _vendedorId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vendedorId");
                OnvendedorIdChanged();
            }
        }
        private global::System.String _vendedorId;
        partial void OnvendedorIdChanging(global::System.String value);
        partial void OnvendedorIdChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.PracticaIS.Model", "FK_ValoracionUsrId", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_ValoracionUsrId", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_ValoracionUsrId", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_ValoracionUsrId", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.PracticaIS.Model.FK_ValoracionUsrId", "UserProfile", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
